# Generated by Django 5.2 on 2025-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('director_name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='movie')),
            ],
        ),
    ]
